<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    public function getLastArticles($numberOfArticles = 3) {


        return $this->findBy(
                        array(), array('createdAt' => 'ASC'), $numberOfArticles, 0
        );
    }

    public function getArchive() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                "SELECT YEAR(a.createdAt) as year,"
                . "COUNT(a.id) as numberOfArticles "
                . "FROM AppBundle:Article as a "
                . "GROUP BY year"
                );
        return$query->getArrayResult();
    }
public function getArticleByTag($tag){
    $qb=$this->createQueryBuilder('a')
            ->select('a')
            ->join('a.tags','t')
            ->where('t.tagName=:tag')
            ->setParameter('tag',$tag);
    return $qb->getQuery()->getResult();
}
}
