<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    /**
     * @param $numberOfArticles
     * @return array
     */
    public function getLastArticles($numberOfArticles){
        return $this->findBy(
            array(),
            array('createdAt' => 'DESC'),
            $numberOfArticles,
            0
        );
    }

    public function getArchive(){
        // Attention, l'utilisation de la fonction YEAR
        // impose l'installation de la bibliothèque
        // orocrm/doctrine-extensions
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "SELECT YEAR(a.createdAt) as year_published,
              COUNT(a.id) as numberOfArticles
              FROM AppBundle:Article as a
              GROUP BY year_published"
        );
        return $query->getArrayResult();
    }


}
